package leetcode;

import java.util.HashMap;

/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
public class FindtheDifference4 {
	public char findTheDifference(String s, String t) {
		int sumOfS = 0, sumOfT=0;
		for (char a : s.toCharArray()) {
			sumOfS += a;
		}
		for (char a : t.toCharArray()) {
			sumOfT += a;
		}
		char diff = (char) (sumOfT - sumOfS);
		return diff;
	}
}
