package leetcode;

import java.util.HashMap;

/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
public class FindtheDifference {
	public char findTheDifference(String s, String t) {
		if (s.isEmpty() && t != null)
			return t.charAt(0);
		HashMap<Character, Integer> map = new HashMap<>();
		for (char a : s.toCharArray()) {
			map.put(a, map.getOrDefault(a, 0) + 1);
		}
		for (char a : t.toCharArray()) {
			if (!map.containsKey(a))
				return a;
			else {
				if (map.get(a) == 0)
					return a;
				map.put(a, map.getOrDefault(a, 0) - 1);
			}
		}
		return t.charAt(t.length()-1);
	}
}
