package leetcode;

import java.util.HashMap;

/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
public class FindtheDifference2 {

	public char findTheDifference(String s, String t) {
		int[] hash = new int[26];
		char[] sarray = s.toCharArray();
		char[] tarray = t.toCharArray();
		for (int i = 0; i < s.length(); i++) {
			int num = sarray[i] - 'a';
			hash[num]++;
		}
		for (int i = 0; i < t.length(); i++) {
			int tnum = tarray[i] - 'a';
			hash[tnum]--;
			if (hash[tnum] < 0) {
				return (char) ((char) tnum + 'a');
			}
		}
		return '-';
	}
}
